# Generated by Django 4.0.3 on 2022-07-06 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='signup_organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_organization', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('Website', models.TextField()),
                ('Email_ID', models.CharField(max_length=100)),
                ('Contact_Number_Organiztion', models.CharField(max_length=13)),
                ('Contact_Person', models.CharField(max_length=50)),
                ('Confirm_Password', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('Organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
