# Generated by Django 4.0.4 on 2022-07-07 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_rename_contact_number_organiztion_signup_organization_contact_number_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_firstname', models.CharField(max_length=50)),
                ('Student_lastname', models.CharField(max_length=50)),
                ('Student_mailid', models.CharField(max_length=100)),
                ('Student_contact_number', models.CharField(max_length=13)),
                ('Student_address', models.TextField()),
                ('Student_org_name', models.CharField(max_length=150)),
                ('Student_dept_name', models.CharField(max_length=50)),
                ('Student_program_id', models.CharField(max_length=50)),
                ('Student_confirm_password', models.CharField(max_length=50)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
