# Generated by Django 4.0.4 on 2022-07-07 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0003_signup_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup_freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Freelancer_name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('Email_ID', models.CharField(max_length=100)),
                ('Contact_Number_Freelancer', models.CharField(max_length=50)),
                ('Confirm_Password', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('Freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
