# Generated by Django 4.0.4 on 2022-07-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_signup_freelancer'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=150)),
                ('paassword', models.CharField(max_length=150)),
            ],
        ),
    ]
