# Generated by Django 4.0.4 on 2022-07-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_login_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org_login_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=150)),
                ('paassword', models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameModel(
            old_name='login_organisation',
            new_name='Flt_login_page',
        ),
    ]
