# Generated by Django 4.0.4 on 2022-07-09 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_org_login_page_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flt_login_page',
        ),
        migrations.DeleteModel(
            name='Org_login_page',
        ),
    ]
